### ISSUE TITLE
初赛最后的杂务活

### ISSUE THREAD

**Issue by Yttehs-HDX** [neuq-rcore/rCore#42]
- [x] 文档完善结束后，合并 `docs`  分支至 `submit-qemu` 分支 #44 
- [x] 将 `submit-qemu` 设置为主分支 （两个平台）
- [x] 删除 Gitlab 镜像仓库存在而 Github 仓库不存在的无用分支

**Comment by Cai1Hsu** [comment]
hb说写完文档最后还要再提交到平台一次

**Comment by xiaocongyaosa** [comment]
独自的我
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "neuq-rcore/rCore"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月29日(星期三) 晚上9:43
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [neuq-rcore/rCore] 初赛最后的杂务活 (Issue #42)





 
hb说写完文档最后还要再提交到平台一次

**Comment by Cai1Hsu** [comment]
还有user可以删了
